/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodms.admin;

import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import oodms.general.WelcomePage;

/**
 *
 * @author User
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminPanel = new javax.swing.JPanel();
        welcomeBackLabel = new javax.swing.JLabel();
        profileIconLabel = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        functionLabel = new javax.swing.JLabel();
        backgroundPanel1 = new javax.swing.JPanel();
        userMgmtBtn = new javax.swing.JLabel();
        catMgmtBtn = new javax.swing.JLabel();
        feedbackMgmtBtn = new javax.swing.JLabel();
        itemMgmtBtn = new javax.swing.JLabel();
        deliveryMgmtBtn = new javax.swing.JLabel();
        customerLabel = new javax.swing.JLabel();
        backgroundPanel2 = new javax.swing.JPanel();
        orderMgmtBtn = new javax.swing.JLabel();
        paymentMgmtBtn = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        backgroundPanel3 = new javax.swing.JPanel();
        customerOrderLabel = new javax.swing.JLabel();
        searchCustomerOrderLabel = new javax.swing.JLabel();
        inputCustomerOrder = new javax.swing.JTextField();
        searchCustomerOrderBtn = new javax.swing.JButton();
        customerPaymentLabel = new javax.swing.JLabel();
        searchCustomerPaymentLabel = new javax.swing.JLabel();
        inputCustomerPayment = new javax.swing.JTextField();
        searchCustomerPaymentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminPanel.setBackground(new java.awt.Color(250, 242, 224));

        welcomeBackLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        welcomeBackLabel.setForeground(new java.awt.Color(76, 43, 24));
        welcomeBackLabel.setText("Welcome back, Admin!");

        profileIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodms/images/admin.png"))); // NOI18N

        logoutBtn.setBackground(new java.awt.Color(184, 145, 104));
        logoutBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(76, 43, 24));
        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        functionLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        functionLabel.setForeground(new java.awt.Color(76, 43, 24));
        functionLabel.setText("Functions");

        backgroundPanel1.setBackground(new java.awt.Color(230, 207, 201));

        userMgmtBtn.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        userMgmtBtn.setForeground(new java.awt.Color(76, 43, 24));
        userMgmtBtn.setText("User Management");

        catMgmtBtn.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        catMgmtBtn.setForeground(new java.awt.Color(76, 43, 24));
        catMgmtBtn.setText("Category Management");

        feedbackMgmtBtn.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        feedbackMgmtBtn.setForeground(new java.awt.Color(76, 43, 24));
        feedbackMgmtBtn.setText("Feedback Management");

        itemMgmtBtn.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        itemMgmtBtn.setForeground(new java.awt.Color(76, 43, 24));
        itemMgmtBtn.setText("Item Management");

        deliveryMgmtBtn.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        deliveryMgmtBtn.setForeground(new java.awt.Color(76, 43, 24));
        deliveryMgmtBtn.setText("Delivery Management");

        javax.swing.GroupLayout backgroundPanel1Layout = new javax.swing.GroupLayout(backgroundPanel1);
        backgroundPanel1.setLayout(backgroundPanel1Layout);
        backgroundPanel1Layout.setHorizontalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliveryMgmtBtn)
                    .addComponent(itemMgmtBtn)
                    .addComponent(feedbackMgmtBtn)
                    .addComponent(catMgmtBtn)
                    .addComponent(userMgmtBtn))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        backgroundPanel1Layout.setVerticalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(userMgmtBtn)
                .addGap(28, 28, 28)
                .addComponent(catMgmtBtn)
                .addGap(28, 28, 28)
                .addComponent(itemMgmtBtn)
                .addGap(27, 27, 27)
                .addComponent(deliveryMgmtBtn)
                .addGap(27, 27, 27)
                .addComponent(feedbackMgmtBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customerLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        customerLabel.setForeground(new java.awt.Color(76, 43, 24));
        customerLabel.setText("Customer");

        backgroundPanel2.setBackground(new java.awt.Color(230, 207, 201));

        orderMgmtBtn.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        orderMgmtBtn.setForeground(new java.awt.Color(76, 43, 24));
        orderMgmtBtn.setText("Order Management");

        paymentMgmtBtn.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        paymentMgmtBtn.setForeground(new java.awt.Color(76, 43, 24));
        paymentMgmtBtn.setText("Payment Management");

        javax.swing.GroupLayout backgroundPanel2Layout = new javax.swing.GroupLayout(backgroundPanel2);
        backgroundPanel2.setLayout(backgroundPanel2Layout);
        backgroundPanel2Layout.setHorizontalGroup(
            backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentMgmtBtn)
                    .addComponent(orderMgmtBtn))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        backgroundPanel2Layout.setVerticalGroup(
            backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(orderMgmtBtn)
                .addGap(28, 28, 28)
                .addComponent(paymentMgmtBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(76, 43, 24));
        searchLabel.setText("Search");

        backgroundPanel3.setBackground(new java.awt.Color(230, 207, 201));

        customerOrderLabel.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        customerOrderLabel.setForeground(new java.awt.Color(76, 43, 24));
        customerOrderLabel.setText("Customer Order");

        searchCustomerOrderLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        searchCustomerOrderLabel.setForeground(new java.awt.Color(76, 43, 24));
        searchCustomerOrderLabel.setText("Search ID:");

        inputCustomerOrder.setBackground(new java.awt.Color(184, 145, 104));
        inputCustomerOrder.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputCustomerOrder.setForeground(new java.awt.Color(76, 43, 24));

        searchCustomerOrderBtn.setBackground(new java.awt.Color(184, 145, 104));
        searchCustomerOrderBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        searchCustomerOrderBtn.setForeground(new java.awt.Color(76, 43, 24));
        searchCustomerOrderBtn.setText("Search");

        customerPaymentLabel.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        customerPaymentLabel.setForeground(new java.awt.Color(76, 43, 24));
        customerPaymentLabel.setText("Customer Payment");

        searchCustomerPaymentLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        searchCustomerPaymentLabel.setForeground(new java.awt.Color(76, 43, 24));
        searchCustomerPaymentLabel.setText("Search ID:");

        inputCustomerPayment.setBackground(new java.awt.Color(184, 145, 104));
        inputCustomerPayment.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputCustomerPayment.setForeground(new java.awt.Color(76, 43, 24));

        searchCustomerPaymentBtn.setBackground(new java.awt.Color(184, 145, 104));
        searchCustomerPaymentBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        searchCustomerPaymentBtn.setForeground(new java.awt.Color(76, 43, 24));
        searchCustomerPaymentBtn.setText("Search");

        javax.swing.GroupLayout backgroundPanel3Layout = new javax.swing.GroupLayout(backgroundPanel3);
        backgroundPanel3.setLayout(backgroundPanel3Layout);
        backgroundPanel3Layout.setHorizontalGroup(
            backgroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel3Layout.createSequentialGroup()
                .addGroup(backgroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(backgroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanel3Layout.createSequentialGroup()
                                .addComponent(searchCustomerPaymentLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputCustomerPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundPanel3Layout.createSequentialGroup()
                                .addComponent(searchCustomerOrderLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputCustomerOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(customerOrderLabel)
                            .addGroup(backgroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(searchCustomerOrderBtn)
                                .addComponent(customerPaymentLabel))))
                    .addGroup(backgroundPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(searchCustomerPaymentBtn)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        backgroundPanel3Layout.setVerticalGroup(
            backgroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(customerOrderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCustomerOrderLabel)
                    .addComponent(inputCustomerOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchCustomerOrderBtn)
                .addGap(57, 57, 57)
                .addComponent(customerPaymentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCustomerPaymentLabel)
                    .addComponent(inputCustomerPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchCustomerPaymentBtn)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addComponent(profileIconLabel)
                        .addGap(39, 39, 39)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoutBtn)
                            .addComponent(welcomeBackLabel)))
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(functionLabel)
                            .addComponent(backgroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerLabel)
                            .addComponent(backgroundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchLabel)
                            .addComponent(backgroundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addComponent(welcomeBackLabel)
                        .addGap(31, 31, 31)
                        .addComponent(logoutBtn))
                    .addComponent(profileIconLabel))
                .addGap(64, 64, 64)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(functionLabel)
                    .addComponent(customerLabel)
                    .addComponent(searchLabel))
                .addGap(18, 18, 18)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(backgroundPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backgroundPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        System.out.println("Logout");
        
        new WelcomePage().setVisible(true);
        dispose();
        
        JOptionPane.showMessageDialog(null, "You have logged out.", "Logout Successful", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
        
        // Set Label Image
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel backgroundPanel1;
    private javax.swing.JPanel backgroundPanel2;
    private javax.swing.JPanel backgroundPanel3;
    private javax.swing.JLabel catMgmtBtn;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JLabel customerOrderLabel;
    private javax.swing.JLabel customerPaymentLabel;
    private javax.swing.JLabel deliveryMgmtBtn;
    private javax.swing.JLabel feedbackMgmtBtn;
    private javax.swing.JLabel functionLabel;
    private javax.swing.JTextField inputCustomerOrder;
    private javax.swing.JTextField inputCustomerPayment;
    private javax.swing.JLabel itemMgmtBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel orderMgmtBtn;
    private javax.swing.JLabel paymentMgmtBtn;
    private javax.swing.JLabel profileIconLabel;
    private javax.swing.JButton searchCustomerOrderBtn;
    private javax.swing.JLabel searchCustomerOrderLabel;
    private javax.swing.JButton searchCustomerPaymentBtn;
    private javax.swing.JLabel searchCustomerPaymentLabel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel userMgmtBtn;
    private javax.swing.JLabel welcomeBackLabel;
    // End of variables declaration//GEN-END:variables
}
