package oodms.admin;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.List;
import java.awt.font.TextAttribute;
import java.text.AttributedString;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import oodms.oop.CountChildren;
import oodms.oop.Create3DArray;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.title.LegendTitle;
import org.jfree.chart.title.TextTitle;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.ui.RectangleInsets;

public class CategorySalesReport extends javax.swing.JFrame {

    /**
     * Creates new form GenderReport
     */
    public CategorySalesReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        targetPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Report based on Category");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        targetPanel.setBackground(new java.awt.Color(184, 145, 104));

        javax.swing.GroupLayout targetPanelLayout = new javax.swing.GroupLayout(targetPanel);
        targetPanel.setLayout(targetPanelLayout);
        targetPanelLayout.setHorizontalGroup(
            targetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        targetPanelLayout.setVerticalGroup(
            targetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(targetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(targetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /**
         * Filter through data to get only item name, the item category and amount payable
         */
        String[][] getOrderArr = new Create3DArray().create3D("/oodms/database/order.txt");
        String[][] getItemArr = new Create3DArray().create3D("/oodms/database/item.txt");
        
        String[][] soldItemArr = new String[getOrderArr.length][3];

        for (int i = 0; i < getOrderArr.length; i++) {
            String itemName = getOrderArr[i][2];
            
            Double totalPrice = Double.valueOf(getOrderArr[i][5]);
            Double countAmountPayable = totalPrice * 1.04 + 5;
            String amountPayable = String.format("%.2f", countAmountPayable);
            
            String itemCategory = "";
            for (int j = 0; j < getItemArr.length; j++) {
                if (getItemArr[j][0].equals(itemName)) {
                    itemCategory = getItemArr[j][2];
                    break;
                }
            }
            
            soldItemArr[i][0] = itemName;
            soldItemArr[i][1] = itemCategory;
            soldItemArr[i][2] = amountPayable;
        }
        
        /**
         * Calculate the total sales of each category
         */
         String[][] getCategoryAvailable = new CountChildren().getCountChildren("/oodms/database/category.txt", 0);
         
         String[][] getCategoryTotalSales = new String[getCategoryAvailable.length][2];
         
         for(int i = 0; i < getCategoryAvailable.length; i++) {
             for(int j = 0; j < soldItemArr.length; j++) {
                 if(soldItemArr[j][1].equals(getCategoryAvailable[i][0])) {
                     getCategoryTotalSales[i][0] = getCategoryAvailable[i][0];
                     
                     if(getCategoryTotalSales[i][1] == null) {
                         getCategoryTotalSales[i][1] = soldItemArr[j][2];
                     } else {
                         Double changedSales = Double.valueOf(getCategoryTotalSales[i][1]);
                         Double incomingSales = Double.valueOf(soldItemArr[j][2]);
                         Double newTotalCategorySales = changedSales + incomingSales;
                         
                         getCategoryTotalSales[i][1] = String.valueOf(newTotalCategorySales);
                     }
                 }
             }
         }
        
         /**
         * Generate the Pie Chart
         */
        // Create dataset
        DefaultPieDataset dataset = new DefaultPieDataset();
        for(String[] categorySales : getCategoryTotalSales) {
            dataset.setValue(categorySales[0], Double.valueOf(categorySales[1]));
        }
        
        // Create pie chart
        JFreeChart chart = ChartFactory.createPieChart(
            "Total Sales for Each Category in Speed Parcel (in RM)", // Chart title
            dataset, // Data
            false, // Include legend
            true, // Tooltips
            false // URLs
        );
        
        // Set background color
        Color brown = new Color(184, 145, 104);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setBackground(brown);
        
        // Set the font for the chart title
        Font titleFont = new Font("Montserrat", Font.BOLD, 24);
        TextTitle title = chart.getTitle();
        title.setFont(titleFont);
        
        // Set the margin for the chart title 
        title.setMargin(50, 50, 0, 50);
        
        // Set the font for the pie section labels
        Font labelFont = new Font("Karla", Font.PLAIN, 14);
        PiePlot plot = (PiePlot) chart.getPlot();
        StandardPieSectionLabelGenerator labelGenerator = new StandardPieSectionLabelGenerator(
            "{0} ({1})", new DecimalFormat("0"), new DecimalFormat("0%")
        );
        plot.setLabelGenerator(labelGenerator);
        plot.setLabelFont(labelFont);
        
        // Set the insets of the chart's plot to add padding
        plot.setInsets(new RectangleInsets(50, 50, 50, 50)); 

        // Change to BorderLayout because the library can't work on default FlowLayout
        targetPanel.setLayout(new BorderLayout());
        targetPanel.add(chartPanel);
        
        // Update the panel display
        targetPanel.revalidate();
        targetPanel.repaint();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategorySalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategorySalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategorySalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategorySalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategorySalesReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel targetPanel;
    // End of variables declaration//GEN-END:variables
}
