/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodms.admin;

import java.awt.Font;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author User
 */
public class DeliveryMgmtDisplay extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryMgmtDisplay
     */
    public DeliveryMgmtDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deliveryMgmtPanel = new javax.swing.JPanel();
        deliveryMgmtLabel = new javax.swing.JLabel();
        searchDeliveryLabel = new javax.swing.JLabel();
        backgroundPanel1 = new javax.swing.JPanel();
        searchDeliveryIDLabel = new javax.swing.JLabel();
        inputDeliveryID = new javax.swing.JTextField();
        searchDeliveryIDBtn = new javax.swing.JButton();
        detailLabel = new javax.swing.JLabel();
        backgroundPanel2 = new javax.swing.JPanel();
        deliveryStaffLabel = new javax.swing.JLabel();
        orderIDLabel = new javax.swing.JLabel();
        orderStatusLabel = new javax.swing.JLabel();
        assignBtn = new javax.swing.JButton();
        modifyBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        dismissBtn = new javax.swing.JButton();
        inputDeliveryStaff = new javax.swing.JComboBox<>();
        inputOrderID = new javax.swing.JComboBox<>();
        inputOrderID1 = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayDeliveryTable = new javax.swing.JTable();
        listDeliveryLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deliveryMgmtPanel.setBackground(new java.awt.Color(250, 242, 224));

        deliveryMgmtLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        deliveryMgmtLabel.setForeground(new java.awt.Color(76, 43, 24));
        deliveryMgmtLabel.setText("Delivery Management");

        searchDeliveryLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        searchDeliveryLabel.setForeground(new java.awt.Color(76, 43, 24));
        searchDeliveryLabel.setText("Search");

        backgroundPanel1.setBackground(new java.awt.Color(230, 207, 201));

        searchDeliveryIDLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        searchDeliveryIDLabel.setForeground(new java.awt.Color(76, 43, 24));
        searchDeliveryIDLabel.setText("Enter ID:");

        inputDeliveryID.setBackground(new java.awt.Color(184, 145, 104));
        inputDeliveryID.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputDeliveryID.setForeground(new java.awt.Color(76, 43, 24));

        searchDeliveryIDBtn.setBackground(new java.awt.Color(184, 145, 104));
        searchDeliveryIDBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        searchDeliveryIDBtn.setForeground(new java.awt.Color(76, 43, 24));
        searchDeliveryIDBtn.setText("Search");

        javax.swing.GroupLayout backgroundPanel1Layout = new javax.swing.GroupLayout(backgroundPanel1);
        backgroundPanel1.setLayout(backgroundPanel1Layout);
        backgroundPanel1Layout.setHorizontalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(searchDeliveryIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputDeliveryID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchDeliveryIDBtn)
                .addGap(16, 16, 16))
        );
        backgroundPanel1Layout.setVerticalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDeliveryIDLabel)
                    .addComponent(inputDeliveryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDeliveryIDBtn))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        detailLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        detailLabel.setForeground(new java.awt.Color(76, 43, 24));
        detailLabel.setText("Details");

        backgroundPanel2.setBackground(new java.awt.Color(230, 207, 201));

        deliveryStaffLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        deliveryStaffLabel.setForeground(new java.awt.Color(76, 43, 24));
        deliveryStaffLabel.setText("Delivery Staff:");

        orderIDLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        orderIDLabel.setForeground(new java.awt.Color(76, 43, 24));
        orderIDLabel.setText("Order ID:");

        orderStatusLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        orderStatusLabel.setForeground(new java.awt.Color(76, 43, 24));
        orderStatusLabel.setText("Order Status:");

        assignBtn.setBackground(new java.awt.Color(184, 145, 104));
        assignBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        assignBtn.setForeground(new java.awt.Color(76, 43, 24));
        assignBtn.setText("Assign");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });

        modifyBtn.setBackground(new java.awt.Color(184, 145, 104));
        modifyBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        modifyBtn.setForeground(new java.awt.Color(76, 43, 24));
        modifyBtn.setText("Modify");
        modifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(184, 145, 104));
        saveBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(76, 43, 24));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        dismissBtn.setBackground(new java.awt.Color(184, 145, 104));
        dismissBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        dismissBtn.setForeground(new java.awt.Color(76, 43, 24));
        dismissBtn.setText("Dismiss");
        dismissBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dismissBtnActionPerformed(evt);
            }
        });

        inputDeliveryStaff.setBackground(new java.awt.Color(184, 145, 104));
        inputDeliveryStaff.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputDeliveryStaff.setForeground(new java.awt.Color(76, 43, 24));
        inputDeliveryStaff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff 1", "Staff 2", "Staff 3", "Staff 4" }));

        inputOrderID.setBackground(new java.awt.Color(184, 145, 104));
        inputOrderID.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputOrderID.setForeground(new java.awt.Color(76, 43, 24));
        inputOrderID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order 1", "Order 2", "Order 3" }));

        inputOrderID1.setBackground(new java.awt.Color(184, 145, 104));
        inputOrderID1.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputOrderID1.setForeground(new java.awt.Color(76, 43, 24));
        inputOrderID1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assigned", "Pending", "Accepted", "Out of Delivery", "Completed" }));

        javax.swing.GroupLayout backgroundPanel2Layout = new javax.swing.GroupLayout(backgroundPanel2);
        backgroundPanel2.setLayout(backgroundPanel2Layout);
        backgroundPanel2Layout.setHorizontalGroup(
            backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanel2Layout.createSequentialGroup()
                        .addComponent(assignBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modifyBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dismissBtn))
                    .addGroup(backgroundPanel2Layout.createSequentialGroup()
                        .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderStatusLabel)
                            .addComponent(orderIDLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deliveryStaffLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputDeliveryStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputOrderID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        backgroundPanel2Layout.setVerticalGroup(
            backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryStaffLabel)
                    .addComponent(inputDeliveryStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderIDLabel)
                    .addComponent(inputOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderStatusLabel)
                    .addComponent(inputOrderID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignBtn)
                    .addComponent(modifyBtn)
                    .addComponent(saveBtn)
                    .addComponent(dismissBtn))
                .addGap(14, 14, 14))
        );

        backBtn.setBackground(new java.awt.Color(184, 145, 104));
        backBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(76, 43, 24));
        backBtn.setText("Back");

        displayDeliveryTable.setBackground(new java.awt.Color(230, 207, 201));
        displayDeliveryTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        displayDeliveryTable.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        displayDeliveryTable.setForeground(new java.awt.Color(76, 43, 24));
        displayDeliveryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"D0001", "John Doe", "Order 2", "Pending"},
                {"D0002", "Alvin Doe", "Order 1", "Assigned"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Delivery ID", "Delivery Staff", "Order ID", "Order Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        displayDeliveryTable.setGridColor(new java.awt.Color(230, 207, 201));
        displayDeliveryTable.setSelectionBackground(new java.awt.Color(184, 145, 104));
        displayDeliveryTable.setSelectionForeground(new java.awt.Color(76, 43, 24));
        displayDeliveryTable.setShowVerticalLines(true);
        jScrollPane2.setViewportView(displayDeliveryTable);
        // Change Table Header Font
        displayDeliveryTable.getTableHeader().setFont(new Font("Karla", Font.PLAIN, 14));

        // Change Table Column Width
        TableColumnModel columnModel = displayDeliveryTable.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(150);
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(2).setPreferredWidth(150);
        columnModel.getColumn(3).setPreferredWidth(150);

        listDeliveryLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        listDeliveryLabel.setForeground(new java.awt.Color(76, 43, 24));
        listDeliveryLabel.setText("List");

        javax.swing.GroupLayout deliveryMgmtPanelLayout = new javax.swing.GroupLayout(deliveryMgmtPanel);
        deliveryMgmtPanel.setLayout(deliveryMgmtPanelLayout);
        deliveryMgmtPanelLayout.setHorizontalGroup(
            deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailLabel)
                    .addComponent(backgroundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backBtn)
                    .addComponent(searchDeliveryLabel)
                    .addComponent(deliveryMgmtLabel)
                    .addComponent(backgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listDeliveryLabel))
                .addGap(31, 31, 31))
        );
        deliveryMgmtPanelLayout.setVerticalGroup(
            deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                .addGroup(deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(deliveryMgmtLabel)
                        .addGap(18, 18, 18)
                        .addComponent(searchDeliveryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backgroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backgroundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(listDeliveryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deliveryMgmtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deliveryMgmtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignBtnActionPerformed

    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void dismissBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dismissBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryMgmtDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryMgmtDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryMgmtDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryMgmtDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryMgmtDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel backgroundPanel1;
    private javax.swing.JPanel backgroundPanel2;
    private javax.swing.JLabel deliveryMgmtLabel;
    private javax.swing.JPanel deliveryMgmtPanel;
    private javax.swing.JLabel deliveryStaffLabel;
    private javax.swing.JLabel detailLabel;
    private javax.swing.JButton dismissBtn;
    private javax.swing.JTable displayDeliveryTable;
    private javax.swing.JTextField inputDeliveryID;
    private javax.swing.JComboBox<String> inputDeliveryStaff;
    private javax.swing.JComboBox<String> inputOrderID;
    private javax.swing.JComboBox<String> inputOrderID1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel listDeliveryLabel;
    private javax.swing.JButton modifyBtn;
    private javax.swing.JLabel orderIDLabel;
    private javax.swing.JLabel orderStatusLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchDeliveryIDBtn;
    private javax.swing.JLabel searchDeliveryIDLabel;
    private javax.swing.JLabel searchDeliveryLabel;
    // End of variables declaration//GEN-END:variables
}
