package oodms.general;

import java.text.DecimalFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFormattedTextField;
import oodms.oop.AddNewCustomer;
import oodms.oop.CheckSimilarity;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import oodms.admin.AdminDashboard;
import oodms.customer.CustomerDashboard;
import oodms.deliver.StaffDashboard;

public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        initComponents();
    }
    
    /**
     * Global variable
     */
    // Boolean for login or signup
    boolean checkLogin = false;
    
    // Send customer username
    private String sendUsername;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        signupBtn = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        confirmPasswordLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        proceedBtn = new javax.swing.JButton();
        inputUsername = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        inputContact = new javax.swing.JTextField();
        inputPassword = new javax.swing.JPasswordField();
        inputConfirmPassword = new javax.swing.JPasswordField();
        inputAddressScrollPanel = new javax.swing.JScrollPane();
        inputAddress = new javax.swing.JTextArea();
        guestBtn = new javax.swing.JButton();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        inputAge = new javax.swing.JSpinner();
        inputGender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Speed Parcel");
        setName(""); // NOI18N

        welcomePanel.setBackground(new java.awt.Color(250, 242, 224));

        welcomeLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(76, 43, 24));
        welcomeLabel.setText("Speed Parcel");

        loginBtn.setBackground(new java.awt.Color(184, 145, 104));
        loginBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(76, 43, 24));
        loginBtn.setText("Log In");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        signupBtn.setBackground(new java.awt.Color(184, 145, 104));
        signupBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(76, 43, 24));
        signupBtn.setText("Sign Up");
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(76, 43, 24));
        usernameLabel.setText("Username:");

        passwordLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(76, 43, 24));
        passwordLabel.setText("Password:");

        confirmPasswordLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        confirmPasswordLabel.setForeground(new java.awt.Color(76, 43, 24));
        confirmPasswordLabel.setText("Confirm Password:");

        emailLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(76, 43, 24));
        emailLabel.setText("Email Address:");

        contactLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        contactLabel.setForeground(new java.awt.Color(76, 43, 24));
        contactLabel.setText("Contact Number:");

        addressLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(76, 43, 24));
        addressLabel.setText("Address:");

        proceedBtn.setBackground(new java.awt.Color(184, 145, 104));
        proceedBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        proceedBtn.setForeground(new java.awt.Color(76, 43, 24));
        proceedBtn.setText("Proceed");
        proceedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedBtnActionPerformed(evt);
            }
        });

        inputUsername.setBackground(new java.awt.Color(230, 207, 201));
        inputUsername.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputUsername.setForeground(new java.awt.Color(76, 43, 24));
        inputUsername.setMinimumSize(new java.awt.Dimension(274, 23));

        inputEmail.setBackground(new java.awt.Color(230, 207, 201));
        inputEmail.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputEmail.setForeground(new java.awt.Color(76, 43, 24));
        inputEmail.setMinimumSize(new java.awt.Dimension(274, 23));
        inputEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputEmailFocusLost(evt);
            }
        });

        inputContact.setBackground(new java.awt.Color(230, 207, 201));
        inputContact.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputContact.setForeground(new java.awt.Color(76, 43, 24));
        inputContact.setMinimumSize(new java.awt.Dimension(274, 23));
        inputContact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputContactFocusLost(evt);
            }
        });

        inputPassword.setBackground(new java.awt.Color(230, 207, 201));
        inputPassword.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputPassword.setForeground(new java.awt.Color(76, 43, 24));
        inputPassword.setMinimumSize(new java.awt.Dimension(274, 23));

        inputConfirmPassword.setBackground(new java.awt.Color(230, 207, 201));
        inputConfirmPassword.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputConfirmPassword.setForeground(new java.awt.Color(76, 43, 24));
        inputConfirmPassword.setMinimumSize(new java.awt.Dimension(274, 23));

        inputAddress.setBackground(new java.awt.Color(230, 207, 201));
        inputAddress.setColumns(20);
        inputAddress.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputAddress.setForeground(new java.awt.Color(76, 43, 24));
        inputAddress.setLineWrap(true);
        inputAddress.setRows(5);
        inputAddressScrollPanel.setViewportView(inputAddress);

        guestBtn.setBackground(new java.awt.Color(184, 145, 104));
        guestBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        guestBtn.setForeground(new java.awt.Color(76, 43, 24));
        guestBtn.setText("Guest");
        guestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestBtnActionPerformed(evt);
            }
        });

        ageLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(76, 43, 24));
        ageLabel.setText("Age:");

        genderLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(76, 43, 24));
        genderLabel.setText("Gender:");

        inputAge.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N

        inputGender.setBackground(new java.awt.Color(230, 207, 201));
        inputGender.setForeground(new java.awt.Color(76, 43, 24));
        inputGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addGap(310, 310, 310))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                        .addComponent(proceedBtn)
                        .addGap(77, 77, 77)
                        .addComponent(guestBtn)
                        .addGap(273, 273, 273))))
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(loginBtn)
                        .addGap(80, 80, 80)
                        .addComponent(signupBtn))
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(confirmPasswordLabel)
                                .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(contactLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(addressLabel)
                            .addComponent(ageLabel)
                            .addComponent(genderLabel))
                        .addGap(18, 18, 18)
                        .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputContact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputAddressScrollPanel)
                            .addComponent(inputUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputAge, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(welcomeLabel)
                .addGap(39, 39, 39)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(signupBtn))
                .addGap(54, 54, 54)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordLabel)
                    .addComponent(inputConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel)
                    .addComponent(inputContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLabel)
                    .addComponent(inputAddressScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(inputAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(inputGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proceedBtn)
                    .addComponent(guestBtn))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        // Check login boolean
        checkLogin = false;

        // Hide Label
        confirmPasswordLabel.setVisible(true);
        emailLabel.setVisible(true);
        contactLabel.setVisible(true);
        addressLabel.setVisible(true);
        ageLabel.setVisible(true);
        genderLabel.setVisible(true);
        
        // Hide Input
        inputConfirmPassword.setVisible(true);
        inputEmail.setVisible(true);
        inputContact.setVisible(true);
        inputAddressScrollPanel.setVisible(true);
        inputAddress.setVisible(true);
        inputAge.setVisible(true);
        inputGender.setVisible(true);
    }//GEN-LAST:event_signupBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // Check login boolean
        checkLogin = true;

        // Show Label
        confirmPasswordLabel.setVisible(false);
        emailLabel.setVisible(false);
        contactLabel.setVisible(false);
        addressLabel.setVisible(false);
        ageLabel.setVisible(false);
        genderLabel.setVisible(false);
        
        // Show Input
        inputConfirmPassword.setVisible(false);
        inputEmail.setVisible(false);
        inputContact.setVisible(false);
        inputAddressScrollPanel.setVisible(false);
        inputAddress.setVisible(false);
        inputAge.setVisible(false);
        inputGender.setVisible(false);
    }//GEN-LAST:event_loginBtnActionPerformed

    private void proceedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedBtnActionPerformed
        if(checkLogin) {
            System.out.println("Login");
            
            // Set input from user
            String getUsername = inputUsername.getText();
            
            char[] targetPassword = inputPassword.getPassword();
            String getPassword = new String(targetPassword);
            
            CheckSimilarity checkExistingUser = new CheckSimilarity();
            boolean loginChecker = checkExistingUser.loginChecker(
                getUsername, 
                getPassword
            );
            
            if(loginChecker) {
                System.out.println("Login successful");
                
                // Decide which dashboard to setVisible
                if(getUsername.toLowerCase().startsWith("admin")) {
                    System.out.println("You are admin.");
                    
                    new AdminDashboard().setVisible(true);
                    dispose();
                } else if(getUsername.toLowerCase().startsWith("delivery")) {
                    System.out.println("You are delivery staff.");
                    
                    sendUsername = getUsername;
                    
                    new StaffDashboard(sendUsername).setVisible(true);
                    dispose();
                } else {
                    System.out.println("You are customer.");
                    
                    sendUsername = getUsername;
                    
                    new CustomerDashboard(sendUsername).setVisible(true);
                    dispose();
                }
                
                // Create a popup dialog message box
                String message = String.join("", "Welcome back, ", String.valueOf(getUsername));
                JOptionPane.showMessageDialog(null, message, "Login Successful", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                // Create a popup dialog mesage box
                JOptionPane.showMessageDialog(null, "Either username or password is incorrect. Please try again", "Error", JOptionPane.ERROR_MESSAGE);
            
                // Clear text field
                inputUsername.setText("");
                inputPassword.setText("");
            }
            
        } else {
            System.out.println("Signup");
            
            // Set input from user
            String getUsername = inputUsername.getText();
            
            char[] targetPassword = inputPassword.getPassword();
            String getPassword = new String(targetPassword);
            
            char[] targetConfirmPassword = inputConfirmPassword.getPassword();
            String getConfirmPassword = new String(targetConfirmPassword);
            
            String getEmail = inputEmail.getText();
            
            String getContact = inputContact.getText();
            
            String getAddress = inputAddress.getText();
            
            String getAge = inputAge.getValue().toString();
            
            String getGender = inputGender.getSelectedItem().toString();
            
            CheckSimilarity checkNewUser = new CheckSimilarity();
            boolean credentialsChecker = checkNewUser.credentialsChecker(
                getUsername, 
                getPassword, 
                getConfirmPassword,
                getEmail
            );
            
            if((!getUsername.equals("")) && (!getPassword.equals("")) && (!getConfirmPassword.equals("")) && (!getEmail.equals("")) && (!getContact.equals("")) && (!getAddress.equals(""))) {
                if(getPassword.equals(getConfirmPassword)) {
                    if((!(Integer.parseInt(getAge) > 100)) && (!(Integer.parseInt(getAge) < 0))) {
                        if(!credentialsChecker) {
                            System.out.println("Added new user");

                            // Create a popup dialog message box
                            JOptionPane.showMessageDialog(null, "Your account has been created. Please login.", "Account Created", JOptionPane.INFORMATION_MESSAGE);

                            AddNewCustomer customer = new AddNewCustomer(getUsername, getPassword, getEmail, getContact, getAddress, getAge, getGender);

                            // Clear text field
                            inputUsername.setText("");
                            inputPassword.setText("");
                            inputConfirmPassword.setText("");
                            inputEmail.setText("");
                            inputContact.setText("");
                            inputAddress.setText("");
                            inputAge.setValue(0);
                            inputGender.setSelectedItem("Male");
                        } else {
                            JOptionPane.showMessageDialog(null, "The username has been taken.", "Existed username", JOptionPane.ERROR_MESSAGE);
                        
                            inputUsername.setText("");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please enter a valid age from range of 0 to 100.", "Invalid age.", JOptionPane.ERROR_MESSAGE);
                    
                        inputAge.setValue(0);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Your password doesn't match. Please re-enter", "Password not match", JOptionPane.ERROR_MESSAGE);
                    
                    inputPassword.setText("");
                    inputConfirmPassword.setText("");
                }
            } else {
                // Create a popup dialog message box
                JOptionPane.showMessageDialog(null, "Account with this username or email existed. Username can't start with Admin or Delivery.\nEnsure your password are the same.\nPlease fill up empty fields.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_proceedBtnActionPerformed

    private void guestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestBtnActionPerformed
        System.out.println("You are now a guest.");
        
        new MarketStorePage(null).setVisible(true);
        dispose();
    }//GEN-LAST:event_guestBtnActionPerformed

    private void inputEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusLost
        if((!inputEmail.getText().contains("@")) || (!inputEmail.getText().contains("."))) {
            JOptionPane.showMessageDialog(null, "Please input a valid email address.", "Invalid email address", JOptionPane.ERROR_MESSAGE);
            
            inputEmail.setText("");
        }
    }//GEN-LAST:event_inputEmailFocusLost

    private void inputContactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputContactFocusLost
        // Define a regular expression pattern for the contact number format
        String contactNumberPattern = "\\d{10}|\\d{11}";
        Pattern pattern = Pattern.compile(contactNumberPattern);

        String contactNumber = inputContact.getText();

         // Use the regular expression to match the contact number
        Matcher matcher = pattern.matcher(contactNumber);
        
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(null, "Please enter the correct contact number format. Examples:\n012xxx1234\nor\n011xxxx1234", "Invalid contact number", JOptionPane.ERROR_MESSAGE);
        
            inputContact.setText("");
        }
    }//GEN-LAST:event_inputContactFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JButton guestBtn;
    private javax.swing.JTextArea inputAddress;
    private javax.swing.JScrollPane inputAddressScrollPanel;
    private javax.swing.JSpinner inputAge;
    private javax.swing.JPasswordField inputConfirmPassword;
    private javax.swing.JTextField inputContact;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JComboBox<String> inputGender;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton proceedBtn;
    private javax.swing.JButton signupBtn;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
