/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodms.deliver;

import java.awt.Font;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author asus
 */
public class DeliveryMgmt extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryMgmt
     */
    public DeliveryMgmt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deliveryMgmtPanel = new javax.swing.JPanel();
        deliveryMgmtLabel = new javax.swing.JLabel();
        backBT = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DeliveryTable = new javax.swing.JTable();
        listDeliveryLabel = new javax.swing.JLabel();
        AcceptBT = new javax.swing.JButton();
        RefreshBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deliveryMgmtPanel.setBackground(new java.awt.Color(250, 242, 224));

        deliveryMgmtLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        deliveryMgmtLabel.setForeground(new java.awt.Color(76, 43, 24));
        deliveryMgmtLabel.setText("Delivery Management");

        backBT.setBackground(new java.awt.Color(184, 145, 104));
        backBT.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        backBT.setForeground(new java.awt.Color(76, 43, 24));
        backBT.setText("Back");
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });

        DeliveryTable.setBackground(new java.awt.Color(230, 207, 201));
        DeliveryTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DeliveryTable.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        DeliveryTable.setForeground(new java.awt.Color(76, 43, 24));
        DeliveryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Delivery ID", "Username", "Address", "Delivery Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DeliveryTable.setGridColor(new java.awt.Color(230, 207, 201));
        DeliveryTable.setSelectionBackground(new java.awt.Color(184, 145, 104));
        DeliveryTable.setSelectionForeground(new java.awt.Color(76, 43, 24));
        DeliveryTable.setShowVerticalLines(true);
        jScrollPane2.setViewportView(DeliveryTable);

        listDeliveryLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        listDeliveryLabel.setForeground(new java.awt.Color(76, 43, 24));
        listDeliveryLabel.setText("Delivery List");

        AcceptBT.setBackground(new java.awt.Color(184, 145, 104));
        AcceptBT.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        AcceptBT.setForeground(new java.awt.Color(76, 43, 24));
        AcceptBT.setText("Accept");
        AcceptBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBTActionPerformed(evt);
            }
        });

        RefreshBT.setBackground(new java.awt.Color(184, 145, 104));
        RefreshBT.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        RefreshBT.setForeground(new java.awt.Color(76, 43, 24));
        RefreshBT.setText("Refresh");
        RefreshBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deliveryMgmtPanelLayout = new javax.swing.GroupLayout(deliveryMgmtPanel);
        deliveryMgmtPanel.setLayout(deliveryMgmtPanelLayout);
        deliveryMgmtPanelLayout.setHorizontalGroup(
            deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                .addGroup(deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deliveryMgmtLabel)
                            .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(listDeliveryLabel))))
                    .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(RefreshBT)
                        .addGap(109, 109, 109)
                        .addComponent(AcceptBT)
                        .addGap(131, 131, 131)
                        .addComponent(backBT)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        deliveryMgmtPanelLayout.setVerticalGroup(
            deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(deliveryMgmtLabel)
                .addGroup(deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(listDeliveryLabel)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(153, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliveryMgmtPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backBT)
                            .addComponent(AcceptBT)
                            .addComponent(RefreshBT))
                        .addGap(63, 63, 63))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deliveryMgmtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deliveryMgmtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBTActionPerformed
        // Refresh Button
        
        // Read File
        
    }//GEN-LAST:event_RefreshBTActionPerformed

    private void AcceptBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBTActionPerformed
        // Accept Button
        
        // Accept order to delivery
        
    }//GEN-LAST:event_AcceptBTActionPerformed

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // Back button
        
        // Back to Dashboard page
        new staffDashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_backBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryMgmt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptBT;
    private javax.swing.JTable DeliveryTable;
    private javax.swing.JButton RefreshBT;
    private javax.swing.JButton backBT;
    private javax.swing.JLabel deliveryMgmtLabel;
    private javax.swing.JPanel deliveryMgmtPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel listDeliveryLabel;
    // End of variables declaration//GEN-END:variables
}
