/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodms.deliver;

import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
import oodms.oop.Create3DArray;
import oodms.oop.SearchFileData;

/**
 *
 * @author asus
 */
public class FeedbackMgmt extends javax.swing.JFrame {

    /**
     * Creates new form FeedbackMgmt
     */
    public FeedbackMgmt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deliveryMgmtPanel = new javax.swing.JPanel();
        FeedbackMgmtLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FeedbackTable = new javax.swing.JTable();
        FeedbackLB = new javax.swing.JLabel();
        backgroundPanel5 = new javax.swing.JPanel();
        searchCustomerNameLabel4 = new javax.swing.JLabel();
        inputCustomerName = new javax.swing.JTextField();
        searchOrderBtn4 = new javax.swing.JButton();
        backBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        deliveryMgmtPanel.setBackground(new java.awt.Color(250, 242, 224));

        FeedbackMgmtLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        FeedbackMgmtLabel.setForeground(new java.awt.Color(76, 43, 24));
        FeedbackMgmtLabel.setText("Feedbacks Management");

        FeedbackTable.setBackground(new java.awt.Color(230, 207, 201));
        FeedbackTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FeedbackTable.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        FeedbackTable.setForeground(new java.awt.Color(76, 43, 24));
        FeedbackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Delivery ID", "Username", "Status", "Feedbacks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FeedbackTable.setGridColor(new java.awt.Color(230, 207, 201));
        FeedbackTable.setSelectionBackground(new java.awt.Color(184, 145, 104));
        FeedbackTable.setSelectionForeground(new java.awt.Color(76, 43, 24));
        FeedbackTable.setShowVerticalLines(true);
        jScrollPane2.setViewportView(FeedbackTable);

        FeedbackLB.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        FeedbackLB.setForeground(new java.awt.Color(76, 43, 24));
        FeedbackLB.setText("Delivery Feedbacks");

        backgroundPanel5.setBackground(new java.awt.Color(230, 207, 201));

        searchCustomerNameLabel4.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        searchCustomerNameLabel4.setForeground(new java.awt.Color(76, 43, 24));
        searchCustomerNameLabel4.setText("Enter Customer Name:");

        inputCustomerName.setBackground(new java.awt.Color(184, 145, 104));
        inputCustomerName.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputCustomerName.setForeground(new java.awt.Color(76, 43, 24));

        searchOrderBtn4.setBackground(new java.awt.Color(184, 145, 104));
        searchOrderBtn4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        searchOrderBtn4.setForeground(new java.awt.Color(76, 43, 24));
        searchOrderBtn4.setText("Search");
        searchOrderBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOrderBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanel5Layout = new javax.swing.GroupLayout(backgroundPanel5);
        backgroundPanel5.setLayout(backgroundPanel5Layout);
        backgroundPanel5Layout.setHorizontalGroup(
            backgroundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel5Layout.createSequentialGroup()
                .addGroup(backgroundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(searchCustomerNameLabel4)
                        .addGap(22, 22, 22)
                        .addComponent(inputCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanel5Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(searchOrderBtn4)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        backgroundPanel5Layout.setVerticalGroup(
            backgroundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(backgroundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCustomerNameLabel4)
                    .addComponent(inputCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(searchOrderBtn4)
                .addGap(14, 14, 14))
        );

        backBT.setBackground(new java.awt.Color(184, 145, 104));
        backBT.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        backBT.setForeground(new java.awt.Color(76, 43, 24));
        backBT.setText("Back");
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deliveryMgmtPanelLayout = new javax.swing.GroupLayout(deliveryMgmtPanel);
        deliveryMgmtPanel.setLayout(deliveryMgmtPanelLayout);
        deliveryMgmtPanelLayout.setHorizontalGroup(
            deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(FeedbackLB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                        .addComponent(FeedbackMgmtLabel)
                        .addGap(45, 511, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliveryMgmtPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                                .addComponent(backgroundPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(backBT))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))))
        );
        deliveryMgmtPanelLayout.setVerticalGroup(
            deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(FeedbackMgmtLabel)
                .addGap(27, 27, 27)
                .addComponent(FeedbackLB)
                .addGroup(deliveryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryMgmtPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(backgroundPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliveryMgmtPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBT)
                        .addGap(52, 52, 52))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deliveryMgmtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deliveryMgmtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // Back button
        
        // Back to Dashboard page
        new staffDashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_backBTActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // When window open
        // Clear JPanel from table
        DefaultTableModel feedbackTable = (DefaultTableModel) FeedbackTable.getModel();
        feedbackTable.setRowCount(0);
        
        // Read text file
        String[][] deliveryArr = new Create3DArray().create3D("/oodms/database/deliveryData.txt");
        
        System.out.println(Arrays.deepToString(deliveryArr));
        
        // Display on table
        for (String[] infoArr : deliveryArr) {
            if(infoArr[4].equals("Out of Delivery")) {
                String[] DLArr = new String[] {infoArr[1], infoArr[2],infoArr[4], infoArr[5]};
                feedbackTable.addRow(DLArr);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void searchOrderBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOrderBtn4ActionPerformed
        // Get Search Input
        String getKeyword = inputCustomerName.getText();

        // Clear table
        DefaultTableModel feedbackTable = (DefaultTableModel) FeedbackTable.getModel();
        feedbackTable.setRowCount(0);

        // OOP Method - Get Searched User Data into Multidimensional Array
        String[][] UserArr = new SearchFileData().searchUsername(getKeyword, "/oodms/database/deliveryData.txt");

        // Loop all data
        for (String[] infoArr : UserArr) {
            String[] DLArr = new String[] {infoArr[1], infoArr[2], infoArr[4], infoArr[5]};
            feedbackTable.addRow(DLArr);
        }
    }//GEN-LAST:event_searchOrderBtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedbackMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedbackMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedbackMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedbackMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeedbackMgmt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FeedbackLB;
    private javax.swing.JLabel FeedbackMgmtLabel;
    private javax.swing.JTable FeedbackTable;
    private javax.swing.JButton backBT;
    private javax.swing.JPanel backgroundPanel5;
    private javax.swing.JPanel deliveryMgmtPanel;
    private javax.swing.JTextField inputCustomerName;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel searchCustomerNameLabel4;
    private javax.swing.JButton searchOrderBtn4;
    // End of variables declaration//GEN-END:variables
}
