/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodms.deliver;

import java.awt.Font;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author asus
 */
public class HistoryMgmt extends javax.swing.JFrame {

    /**
     * Creates new form HistoryMgmt
     */
    public HistoryMgmt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HistoryMgmtPanel = new javax.swing.JPanel();
        historyMgmtLabel = new javax.swing.JLabel();
        backBT = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();
        listDeliveryLabel = new javax.swing.JLabel();
        VFeedbackBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        HistoryMgmtPanel.setBackground(new java.awt.Color(250, 242, 224));

        historyMgmtLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        historyMgmtLabel.setForeground(new java.awt.Color(76, 43, 24));
        historyMgmtLabel.setText("History Management");

        backBT.setBackground(new java.awt.Color(184, 145, 104));
        backBT.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        backBT.setForeground(new java.awt.Color(76, 43, 24));
        backBT.setText("Back");
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });

        HistoryTable.setBackground(new java.awt.Color(230, 207, 201));
        HistoryTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HistoryTable.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        HistoryTable.setForeground(new java.awt.Color(76, 43, 24));
        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Delivery ID", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        HistoryTable.setGridColor(new java.awt.Color(230, 207, 201));
        HistoryTable.setSelectionBackground(new java.awt.Color(184, 145, 104));
        HistoryTable.setSelectionForeground(new java.awt.Color(76, 43, 24));
        HistoryTable.setShowVerticalLines(true);
        jScrollPane2.setViewportView(HistoryTable);

        listDeliveryLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        listDeliveryLabel.setForeground(new java.awt.Color(76, 43, 24));
        listDeliveryLabel.setText("Delivery History");

        VFeedbackBT.setBackground(new java.awt.Color(184, 145, 104));
        VFeedbackBT.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        VFeedbackBT.setForeground(new java.awt.Color(76, 43, 24));
        VFeedbackBT.setText("View Feedback");
        VFeedbackBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VFeedbackBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HistoryMgmtPanelLayout = new javax.swing.GroupLayout(HistoryMgmtPanel);
        HistoryMgmtPanel.setLayout(HistoryMgmtPanelLayout);
        HistoryMgmtPanelLayout.setHorizontalGroup(
            HistoryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryMgmtPanelLayout.createSequentialGroup()
                .addGroup(HistoryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HistoryMgmtPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(HistoryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(historyMgmtLabel)
                            .addGroup(HistoryMgmtPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(listDeliveryLabel))))
                    .addGroup(HistoryMgmtPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HistoryMgmtPanelLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(VFeedbackBT)
                        .addGap(151, 151, 151)
                        .addComponent(backBT)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        HistoryMgmtPanelLayout.setVerticalGroup(
            HistoryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryMgmtPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(historyMgmtLabel)
                .addGroup(HistoryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HistoryMgmtPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(listDeliveryLabel)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(143, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoryMgmtPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(HistoryMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backBT)
                            .addComponent(VFeedbackBT))
                        .addGap(63, 63, 63))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HistoryMgmtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HistoryMgmtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VFeedbackBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VFeedbackBTActionPerformed
        // View Feedback button

        // Go to feedback page
        new FeedbackMgmt().setVisible(true);
        dispose();
    }//GEN-LAST:event_VFeedbackBTActionPerformed

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // Back button

        // Back to Dashboard page
        new staffDashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_backBTActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryMgmt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HistoryMgmtPanel;
    private javax.swing.JTable HistoryTable;
    private javax.swing.JButton VFeedbackBT;
    private javax.swing.JButton backBT;
    private javax.swing.JLabel historyMgmtLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel listDeliveryLabel;
    // End of variables declaration//GEN-END:variables
}
