package oodms.deliver;

import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import oodms.general.WelcomePage;
import oodms.oop.Create3DArray;
import oodms.oop.MouseHover;

public class StaffDashboard extends javax.swing.JFrame {
    
    // Accept staff username
    private static String acceptUsername;

    /**
     * Creates new form StaffDashboard
     * @param acceptUsername
     */
    public StaffDashboard(String acceptUsername) {
        initComponents();
        
        StaffDashboard.acceptUsername = acceptUsername;
        
        staffUsernameLabel.setText(acceptUsername);
        
        // Add mouse hover event
        String[] componentTexts = new String[] {
            "Delivery Management",
            "View Feedback"
        };
                
        JPanel[] allJPanel = new JPanel[] {backgroundPanel1};
        
        MouseHover mh = new MouseHover();
        mh.mouseHoverEffect(componentTexts, allJPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StaffPanel = new javax.swing.JPanel();
        welcomeBackLabel = new javax.swing.JLabel();
        profileIconLabel = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        functionLabel = new javax.swing.JLabel();
        backgroundPanel1 = new javax.swing.JPanel();
        deliveryMgmtBtn = new javax.swing.JLabel();
        viewFeedbackBtn = new javax.swing.JLabel();
        pendingLabel = new javax.swing.JLabel();
        deliveringLabel = new javax.swing.JLabel();
        staffUsernameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayDeliveringTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayPendingTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff Dashboard");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        StaffPanel.setBackground(new java.awt.Color(250, 242, 224));

        welcomeBackLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        welcomeBackLabel.setForeground(new java.awt.Color(76, 43, 24));
        welcomeBackLabel.setText("Welcome back!");

        profileIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodms/images/staff.png"))); // NOI18N

        logoutBtn.setBackground(new java.awt.Color(184, 145, 104));
        logoutBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(76, 43, 24));
        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        functionLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        functionLabel.setForeground(new java.awt.Color(76, 43, 24));
        functionLabel.setText("Functions");

        backgroundPanel1.setBackground(new java.awt.Color(230, 207, 201));

        deliveryMgmtBtn.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        deliveryMgmtBtn.setForeground(new java.awt.Color(76, 43, 24));
        deliveryMgmtBtn.setText("Delivery Management");
        deliveryMgmtBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveryMgmtBtnMouseClicked(evt);
            }
        });

        viewFeedbackBtn.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        viewFeedbackBtn.setForeground(new java.awt.Color(76, 43, 24));
        viewFeedbackBtn.setText("View Feedback");
        viewFeedbackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewFeedbackBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanel1Layout = new javax.swing.GroupLayout(backgroundPanel1);
        backgroundPanel1.setLayout(backgroundPanel1Layout);
        backgroundPanel1Layout.setHorizontalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewFeedbackBtn)
                    .addComponent(deliveryMgmtBtn))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        backgroundPanel1Layout.setVerticalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(deliveryMgmtBtn)
                .addGap(29, 29, 29)
                .addComponent(viewFeedbackBtn)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        pendingLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        pendingLabel.setForeground(new java.awt.Color(76, 43, 24));
        pendingLabel.setText("Pending Accept");

        deliveringLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        deliveringLabel.setForeground(new java.awt.Color(76, 43, 24));
        deliveringLabel.setText("Delivering");

        staffUsernameLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        staffUsernameLabel.setForeground(new java.awt.Color(76, 43, 24));
        staffUsernameLabel.setText("Username");

        displayDeliveringTable.setBackground(new java.awt.Color(230, 207, 201));
        displayDeliveringTable.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        displayDeliveringTable.setForeground(new java.awt.Color(76, 43, 24));
        displayDeliveringTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer", "Address", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(displayDeliveringTable);
        // Change Table Header Font
        displayDeliveringTable.getTableHeader().setFont(new Font("Karla", Font.PLAIN, 14));

        // Change Table Column Width
        TableColumnModel columnModel2 = displayDeliveringTable.getColumnModel();

        columnModel2.getColumn(0).setPreferredWidth(75);
        columnModel2.getColumn(1).setPreferredWidth(100);
        columnModel2.getColumn(2).setPreferredWidth(200);
        columnModel2.getColumn(3).setPreferredWidth(75);

        displayPendingTable.setBackground(new java.awt.Color(230, 207, 201));
        displayPendingTable.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        displayPendingTable.setForeground(new java.awt.Color(76, 43, 24));
        displayPendingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer", "Address", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(displayPendingTable);
        // Change Table Header Font
        displayPendingTable.getTableHeader().setFont(new Font("Karla", Font.PLAIN, 14));

        // Change Table Column Width
        TableColumnModel columnModel = displayPendingTable.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(75);;
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(2).setPreferredWidth(200);
        columnModel.getColumn(3).setPreferredWidth(75);

        javax.swing.GroupLayout StaffPanelLayout = new javax.swing.GroupLayout(StaffPanel);
        StaffPanel.setLayout(StaffPanelLayout);
        StaffPanelLayout.setHorizontalGroup(
            StaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StaffPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(StaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StaffPanelLayout.createSequentialGroup()
                        .addComponent(profileIconLabel)
                        .addGap(39, 39, 39)
                        .addGroup(StaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoutBtn)
                            .addGroup(StaffPanelLayout.createSequentialGroup()
                                .addComponent(welcomeBackLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(staffUsernameLabel))))
                    .addGroup(StaffPanelLayout.createSequentialGroup()
                        .addGroup(StaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(functionLabel)
                            .addComponent(backgroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(StaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pendingLabel)
                            .addComponent(deliveringLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        StaffPanelLayout.setVerticalGroup(
            StaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StaffPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(StaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StaffPanelLayout.createSequentialGroup()
                        .addGroup(StaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(welcomeBackLabel)
                            .addComponent(staffUsernameLabel))
                        .addGap(31, 31, 31)
                        .addComponent(logoutBtn))
                    .addComponent(profileIconLabel))
                .addGap(64, 64, 64)
                .addGroup(StaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(functionLabel)
                    .addComponent(pendingLabel))
                .addGap(18, 18, 18)
                .addGroup(StaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backgroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StaffPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deliveringLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(StaffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(StaffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deliveryMgmtBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryMgmtBtnMouseClicked
        new DeliveryMgmtDisplay(acceptUsername).setVisible(true);
        dispose();
    }//GEN-LAST:event_deliveryMgmtBtnMouseClicked

    private void viewFeedbackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewFeedbackBtnMouseClicked
        new FeedbackViewDisplay(acceptUsername).setVisible(true);
        dispose();
    }//GEN-LAST:event_viewFeedbackBtnMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String[][] getDeliveryDataArr = new Create3DArray().create3D("/oodms/database/delivery.txt");
        
        DefaultTableModel pendingTable = (DefaultTableModel) displayPendingTable.getModel();
        DefaultTableModel deliveringTable = (DefaultTableModel) displayDeliveringTable.getModel();
        
        pendingTable.setRowCount(0);
        deliveringTable.setRowCount(0);
        
        for(String[] getDeliveryData : getDeliveryDataArr) {
            if(getDeliveryData[0].equals(acceptUsername)) {
                if(getDeliveryData[2].equals("Unassigned")) {
                    String[] pendingArr = new String[] {getDeliveryData[1], getDeliveryData[3], getDeliveryData[4], getDeliveryData[2]};
                    pendingTable.addRow(pendingArr);
                    
                } else if(getDeliveryData[2].equals("Ongoing")) {
                    String[] deliveringArr = new String[] {getDeliveryData[1], getDeliveryData[3], getDeliveryData[4], getDeliveryData[2]};
                    deliveringTable.addRow(deliveringArr);
                } else {
                    System.out.println("No orders");
                }
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        new WelcomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffDashboard(acceptUsername).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StaffPanel;
    private javax.swing.JPanel backgroundPanel1;
    private javax.swing.JLabel deliveringLabel;
    private javax.swing.JLabel deliveryMgmtBtn;
    private javax.swing.JTable displayDeliveringTable;
    private javax.swing.JTable displayPendingTable;
    private javax.swing.JLabel functionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel pendingLabel;
    private javax.swing.JLabel profileIconLabel;
    private javax.swing.JLabel staffUsernameLabel;
    private javax.swing.JLabel viewFeedbackBtn;
    private javax.swing.JLabel welcomeBackLabel;
    // End of variables declaration//GEN-END:variables
}
