/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodms.admin;

import java.awt.Font;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author User
 */
public class PaymentMgmtDisplay extends javax.swing.JFrame {

    /**
     * Creates new form PaymentMgmtDisplay
     */
    public PaymentMgmtDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentMgmtPanel = new javax.swing.JPanel();
        paymentMgmtLabel = new javax.swing.JLabel();
        searchPaymentLabel = new javax.swing.JLabel();
        backgroundPanel1 = new javax.swing.JPanel();
        searchCustomerNameLabel = new javax.swing.JLabel();
        inputCustomerName = new javax.swing.JTextField();
        searchPaymentBtn = new javax.swing.JButton();
        orderDateLabel = new javax.swing.JLabel();
        inputOrderID = new javax.swing.JTextField();
        detailLabel = new javax.swing.JLabel();
        backgroundPanel2 = new javax.swing.JPanel();
        itemNameLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        inputItemName = new javax.swing.JTextField();
        inputQuantity = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        inputPrice = new javax.swing.JTextField();
        totalPriceLabel = new javax.swing.JLabel();
        inputTotalPrice = new javax.swing.JTextField();
        amountPayableLabel = new javax.swing.JLabel();
        inputAmountPayable = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        listPaymentLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayPaymentTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paymentMgmtPanel.setBackground(new java.awt.Color(250, 242, 224));

        paymentMgmtLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        paymentMgmtLabel.setForeground(new java.awt.Color(76, 43, 24));
        paymentMgmtLabel.setText("Payment Management");

        searchPaymentLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        searchPaymentLabel.setForeground(new java.awt.Color(76, 43, 24));
        searchPaymentLabel.setText("Search");

        backgroundPanel1.setBackground(new java.awt.Color(230, 207, 201));

        searchCustomerNameLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        searchCustomerNameLabel.setForeground(new java.awt.Color(76, 43, 24));
        searchCustomerNameLabel.setText("Enter Customer Name:");

        inputCustomerName.setBackground(new java.awt.Color(184, 145, 104));
        inputCustomerName.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputCustomerName.setForeground(new java.awt.Color(76, 43, 24));

        searchPaymentBtn.setBackground(new java.awt.Color(184, 145, 104));
        searchPaymentBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        searchPaymentBtn.setForeground(new java.awt.Color(76, 43, 24));
        searchPaymentBtn.setText("Search");

        orderDateLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        orderDateLabel.setForeground(new java.awt.Color(76, 43, 24));
        orderDateLabel.setText("Order ID:");

        inputOrderID.setBackground(new java.awt.Color(184, 145, 104));
        inputOrderID.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputOrderID.setForeground(new java.awt.Color(76, 43, 24));

        javax.swing.GroupLayout backgroundPanel1Layout = new javax.swing.GroupLayout(backgroundPanel1);
        backgroundPanel1.setLayout(backgroundPanel1Layout);
        backgroundPanel1Layout.setHorizontalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orderDateLabel)
                    .addComponent(searchCustomerNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(inputOrderID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(searchPaymentBtn)
                .addGap(16, 16, 16))
        );
        backgroundPanel1Layout.setVerticalGroup(
            backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCustomerNameLabel)
                    .addComponent(inputCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPaymentBtn))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderDateLabel)
                    .addComponent(inputOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        detailLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        detailLabel.setForeground(new java.awt.Color(76, 43, 24));
        detailLabel.setText("Details");

        backgroundPanel2.setBackground(new java.awt.Color(230, 207, 201));

        itemNameLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        itemNameLabel.setForeground(new java.awt.Color(76, 43, 24));
        itemNameLabel.setText("Payment Date:");

        quantityLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        quantityLabel.setForeground(new java.awt.Color(76, 43, 24));
        quantityLabel.setText("Process Fees (4%):");

        inputItemName.setEditable(false);
        inputItemName.setBackground(new java.awt.Color(184, 145, 104));
        inputItemName.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputItemName.setForeground(new java.awt.Color(76, 43, 24));

        inputQuantity.setEditable(false);
        inputQuantity.setBackground(new java.awt.Color(184, 145, 104));
        inputQuantity.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputQuantity.setForeground(new java.awt.Color(76, 43, 24));

        priceLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(76, 43, 24));
        priceLabel.setText("Shipment Fees:");

        inputPrice.setEditable(false);
        inputPrice.setBackground(new java.awt.Color(184, 145, 104));
        inputPrice.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputPrice.setForeground(new java.awt.Color(76, 43, 24));

        totalPriceLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        totalPriceLabel.setForeground(new java.awt.Color(76, 43, 24));
        totalPriceLabel.setText("Total Price (RM):");

        inputTotalPrice.setEditable(false);
        inputTotalPrice.setBackground(new java.awt.Color(184, 145, 104));
        inputTotalPrice.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputTotalPrice.setForeground(new java.awt.Color(76, 43, 24));

        amountPayableLabel.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        amountPayableLabel.setForeground(new java.awt.Color(76, 43, 24));
        amountPayableLabel.setText("Amount Payable:");

        inputAmountPayable.setEditable(false);
        inputAmountPayable.setBackground(new java.awt.Color(184, 145, 104));
        inputAmountPayable.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        inputAmountPayable.setForeground(new java.awt.Color(76, 43, 24));

        javax.swing.GroupLayout backgroundPanel2Layout = new javax.swing.GroupLayout(backgroundPanel2);
        backgroundPanel2.setLayout(backgroundPanel2Layout);
        backgroundPanel2Layout.setHorizontalGroup(
            backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(amountPayableLabel)
                    .addComponent(totalPriceLabel)
                    .addComponent(priceLabel)
                    .addComponent(itemNameLabel)
                    .addComponent(quantityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(inputPrice, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(inputItemName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(inputQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(inputTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputAmountPayable, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        backgroundPanel2Layout.setVerticalGroup(
            backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameLabel)
                    .addComponent(inputItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel)
                    .addComponent(inputQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(inputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPriceLabel)
                    .addComponent(inputTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountPayableLabel)
                    .addComponent(inputAmountPayable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        backBtn.setBackground(new java.awt.Color(184, 145, 104));
        backBtn.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(76, 43, 24));
        backBtn.setText("Back");

        listPaymentLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        listPaymentLabel.setForeground(new java.awt.Color(76, 43, 24));
        listPaymentLabel.setText("List");

        displayPaymentTable.setBackground(new java.awt.Color(230, 207, 201));
        displayPaymentTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        displayPaymentTable.setFont(new java.awt.Font("Karla", 0, 14)); // NOI18N
        displayPaymentTable.setForeground(new java.awt.Color(76, 43, 24));
        displayPaymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PY0001", "OR0001", "John Doe", "30-01-2023"},
                {"PY0002", "OR0002", "Alvin Doe", "19-01-2023"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Payment ID", "Order ID", "Customer Name", "Payment Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        displayPaymentTable.setGridColor(new java.awt.Color(230, 207, 201));
        displayPaymentTable.setSelectionBackground(new java.awt.Color(184, 145, 104));
        displayPaymentTable.setSelectionForeground(new java.awt.Color(76, 43, 24));
        displayPaymentTable.setShowVerticalLines(true);
        jScrollPane2.setViewportView(displayPaymentTable);
        // Change Table Header Font
        displayPaymentTable.getTableHeader().setFont(new Font("Karla", Font.PLAIN, 14));

        // Change Table Column Width
        TableColumnModel columnModel = displayPaymentTable.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(100);
        columnModel.getColumn(1).setPreferredWidth(125);
        columnModel.getColumn(2).setPreferredWidth(125);
        columnModel.getColumn(3).setPreferredWidth(125);

        javax.swing.GroupLayout paymentMgmtPanelLayout = new javax.swing.GroupLayout(paymentMgmtPanel);
        paymentMgmtPanel.setLayout(paymentMgmtPanelLayout);
        paymentMgmtPanelLayout.setHorizontalGroup(
            paymentMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentMgmtPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(paymentMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentMgmtPanelLayout.createSequentialGroup()
                        .addGroup(paymentMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn)
                            .addComponent(paymentMgmtLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paymentMgmtPanelLayout.createSequentialGroup()
                        .addGroup(paymentMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchPaymentLabel)
                            .addComponent(detailLabel)
                            .addComponent(backgroundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(paymentMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listPaymentLabel))
                        .addGap(29, 29, 29))))
        );
        paymentMgmtPanelLayout.setVerticalGroup(
            paymentMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentMgmtPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(paymentMgmtLabel)
                .addGap(18, 18, 18)
                .addGroup(paymentMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchPaymentLabel)
                    .addComponent(listPaymentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paymentMgmtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentMgmtPanelLayout.createSequentialGroup()
                        .addComponent(backgroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(detailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backgroundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentMgmtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentMgmtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentMgmtDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentMgmtDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentMgmtDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentMgmtDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentMgmtDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountPayableLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel backgroundPanel1;
    private javax.swing.JPanel backgroundPanel2;
    private javax.swing.JLabel detailLabel;
    private javax.swing.JTable displayPaymentTable;
    private javax.swing.JTextField inputAmountPayable;
    private javax.swing.JTextField inputCustomerName;
    private javax.swing.JTextField inputItemName;
    private javax.swing.JTextField inputOrderID;
    private javax.swing.JTextField inputPrice;
    private javax.swing.JTextField inputQuantity;
    private javax.swing.JTextField inputTotalPrice;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel listPaymentLabel;
    private javax.swing.JLabel orderDateLabel;
    private javax.swing.JLabel paymentMgmtLabel;
    private javax.swing.JPanel paymentMgmtPanel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel searchCustomerNameLabel;
    private javax.swing.JButton searchPaymentBtn;
    private javax.swing.JLabel searchPaymentLabel;
    private javax.swing.JLabel totalPriceLabel;
    // End of variables declaration//GEN-END:variables
}
